# docker-compose.yml

version: "3"
services:
  app:
    build: ./express
    container_name: chapp
    hostname: chapp
    ports:
      - "3000:3000"
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - '27018:27017'
volumes:
  mongodata: